{% set name = "flask-minify" %}
{% set version = "0.42" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Flask-Minify-{{ version }}.tar.gz
  sha256: cdae9bd492b4200ebbf9fd0b08878452274ddca454f3eb1dff8b900629538c8b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - flask
    - htmlmin
    - jsmin
    - lesscpy
    - python >={{ python_min }}
    - rcssmin
    - six
    - python-xxhash

test:
  imports:
    - flask_minify
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mrf345/flask_minify/
  summary: Flask extension to minify html, css, js and less.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - taluripooja
